app:
  app_name: "Translate API"
  debug: true
  host: "127.0.0.1"
  port: 8000
  reload: true
  log_level: "info"
  version: "0.1.0"

# AI模型配置
ai_model:
  # 默认使用的模型
  default_model: "dashscope"
  
  # 阿里云DashScope配置（通义千问）
  dashscope:
    service_type: "dashscope"  # 添加服务类型
    #api_key: "sk-7a3acac23fd24d7eb382f7196096eeae"  # 从环境变量获取
    api_key: {DASHSCOPE_API_KEY}  # 从环境变量获取
    base_url: {DASHSCOPE_BASE_URL}  # 修复：使用兼容模式URL
    model: "qwen-plus"
    temperature: 0.3
    max_tokens: 2000
    timeout: 60  # 增加超时时间



  
#  # OpenAI配置
#  openai:
#    service_type: "openai"  # 添加服务类型
#    api_key: "${OPENAI_API_KEY}"  # 从环境变量获取
#    base_url: "https://api.openai.com/v1"  # 支持第三方兼容API
#    model: "gpt-3.5-turbo"
#    temperature: 0.3
#    max_tokens: 2000
#    timeout: 60  # 增加超时时间
#    timeout: 30
#
#  # 智谱AI配置
#  zhipuai:
#    api_key: "${ZHIPUAI_API_KEY}"
#    model: "glm-4"
#    temperature: 0.3
#    max_tokens: 2000
#    timeout: 30
#
#  # Ollama本地模型配置
#  ollama:
#    base_url: "http://localhost:11434"
#    model: "llama2"
#    temperature: 0.3
#    timeout: 60
#
#  # Azure OpenAI配置
#  azure_openai:
#    api_key: "${AZURE_OPENAI_API_KEY}"
#    endpoint: "${AZURE_OPENAI_ENDPOINT}"
#    api_version: "2024-02-01"
#    deployment_name: "gpt-35-turbo"
#    temperature: 0.3
#    max_tokens: 2000

## 数据库配置 (预留)
#database:
#  url: "sqlite:///./app.db"
#  echo: false
#
## Redis 配置 (预留)
#redis:
#  host: "127.0.0.1"
#  port: 6379
#  db: 0
#
## 安全配置 (预留)
#security:
#  secret_key: "your-secret-key-here"
#  algorithm: "HS256"
#  access_token_expire_minutes: 30

